version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 2
    target-branch: "develop"
    labels:
      - "npm dependencies"
    reviewers:
     - "kleva-j"
    assignees:
      - "kleva-j"
